---
- hosts: coreos
  gather_facts: false
  roles:
  - vmware.coreos-bootstrap
  tasks:
  - name: install httplib2
    pip: name=httplib2

- hosts: etcd
  sudo: yes
  roles:
  - etcd-node
    
- hosts: master
  sudo: yes
  roles:
  - kubernetes-master
  - kubernetes-master/cloud-config

- hosts: minions
  gather_facts: true
  sudo: yes
  roles:
  - kubernetes-worker/cloud-config
  - kubernetes-worker

