- name: create master keys directory
  file: name=/etc/kubernetes/ssl/ state=directory

- name: set up master TLS assets
  copy: src={{LOCAL_SSL_DIR}}/{{item}} dest=/etc/kubernetes/ssl/{{item}}
  with_items:
  - ca.pem
  - apiserver.pem
  - apiserver-key.pem

