- name: create manifests directory
  file: name=/etc/kubernetes/manifests state=directory

- name: create schduler pod manifest
  template: src=kube-scheduler.yaml.j2 dest=/etc/kubernetes/manifests/kube-scheduler.yaml

