- name: create directories
  file: name={{item}} state=directory
  with_items:
  - /etc/flannel
  - /etc/systemd/system/flanneld.service.d/
  - /etc/systemd/system/docker.service.d/

- name: install options.env
  template: 
    src=options.env.j2 dest=/etc/flannel/options.env
  notify: daemon-reload

- name: install 40-ExecStartPre-symlink.conf
  copy:
    src=40-ExecStartPre-symlink.conf dest=/etc/systemd/system/flanneld.service.d/
  notify: daemon-reload

- name: install 40-flannel.conf
  copy:
    src=40-flannel.conf dest=/etc/systemd/system/docker.service.d/
  notify: daemon-reload

- name: get netconfig 
  command: etcdctl mk /coreos.com/network/config '{"Network":"{{POD_NETWORK}}"}'
  ignore_errors: yes
  when: "'master' in group_names"

- name: ensure flanneld is running
  service: name=flanneld state=started

